# Generated by Django 5.2.1 on 2025-05-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agregar_maquina", "0002_maquina_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquina",
            name="numero_de_serie",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
